site_name: "Generalized Nash Equilibrium Solver"

theme:
  name: material
  palette:
    primary: blue grey
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

plugins:
  - awesome-pages
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_toc_entry: false
            show_signature_annotations: true
            separate_signature: true
            show_category_heading: false   # adds "Classes", "Functions", "Methods"
            show_submodules: false
            show_bases: false
            show_source: false
            show_source_order: true
            members_order: source

markdown_extensions:
  - toc
  - attr_list

# Global site menu
# https://www.mkdocs.org/user-guide/writing-your-docs/#file-layout
nav:
  - Home: index.md
  - Installation: installation.md
  - Reference:
      - Functions :
          - Construct Vectors: development/reference/functions/construct_vectors.md
          - Created Wrapped Function: development/reference/functions/create_wrapped_function.md
          - Flatten Variables: development/reference/functions/flatten_variables.md
          - One Hot Encoding: development/reference/functions/one_hot_encoding.md
          - Create Single Wrapped Function: development/reference/functions/wrapped_function_single.md








  - Examples: examples.md
  - Development:
      - Overview: development/overview.md
      - Standards: development/standards.md