site_name: "Generalized Nash Equilibrium Solver"

theme:
  name: material
  palette:
    primary: blue grey
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

plugins:
  - awesome-pages
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_toc_entry: false
            show_signature_annotations: true
            separate_signature: true
            show_category_heading: false   # adds "Classes", "Functions", "Methods"
            show_submodules: false
            show_bases: false
            show_source: false
            show_source_order: true
            members_order: source

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc
  - attr_list
  
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6


  

# Global site menu
# https://www.mkdocs.org/user-guide/writing-your-docs/#file-layout
nav:
  - Home: index.md
  - Installation: installation.md
  - Reference:
      - Functions:
          - Construct Vectors: documentation/functions/construct_vectors.md
          - Created Wrapped Function: documentation/functions/create_wrapped_function.md
          - Flatten Variables: documentation/functions/flatten_variables.md
          - One Hot Encoding: documentation/functions/one_hot_encoding.md
          - Create Single Wrapped Function: documentation/functions/wrapped_function_single.md
      - Solvers:
          - Bounded Solver: documentation/solvers/bounded.md
          - Unbounded Solver: documentation/solvers/unbounded.md
      - Types:
          - Object Types: documentation/types/object_types.md
          - Function Types: documentation/types/type_functions.md

  - Examples: examples.md
  - Development:
      - Overview: development/overview.md
      - Standards: development/standards.md