site_name: "Generalized Nash Equilibrium Solver"

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_toc_entry: true
            show_signature_annotations: true
            show_source: false

# Global site menu
# https://www.mkdocs.org/user-guide/writing-your-docs/#file-layout
nav:
  - Home: index.md
  - API Reference: reference.md