site_name: "Generalized Nash Equilibrium Solver"

theme:
  name: material
  palette:
    primary: blue grey
  features:
    - navigation.tabs

plugins:
  - awesome-pages
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_toc_entry: true
            show_signature_annotations: true
            show_source: false

# Global site menu
# https://www.mkdocs.org/user-guide/writing-your-docs/#file-layout
nav:
  - Home: index.md
  - User Guide: user_guide.md
  - Installation: installation.md
  - API Reference: reference.md
  - Examples: examples.md
  - Development:
      - Overview: development/overview.md
      - Standards: development/standards.md