site_name: "Generalized Nash Equilibrium Solver"

theme:
  name: material
  palette:
    primary: blue grey
  features:
    - navigation.tabs

plugins:
  - awesome-pages
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_toc_entry: false
            show_signature_annotations: true
            separate_signature: true
            show_category_heading: false   # adds "Classes", "Functions", "Methods"
            show_submodules: false
            show_bases: false
            show_source: false
            show_source_order: true
            members_order: source

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6



# Global site menu
# https://www.mkdocs.org/user-guide/writing-your-docs/#file-layout
nav:
  - Home: index.md
  - User Guide: user_guide.md
  - Installation: installation.md
  - Reference: reference.md
  - Examples: examples.md
  - Development:
      - Overview: development/overview.md
      - Standards: development/standards.md